### ISSUE TITLE
Generate new ArcLight application and deploy it

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/stanford-arclight#1]
* [x] Generate new application 
* [x] Generate configuration files for sul-solr
  * https://github.com/sul-dlss/sul-solr-configs/pull/135
* [x] Create a new Solr collection
* [x] Crib remaining ArcLight config files from existing arclight-demo app or w/ @anarchivist's input
* [x] Deploy application to demo & prod

**Comment by anarchivist** [comment]
see also sul-dlss/operations-tasks#1605 and sul-dlss/operations-tasks#340

**Comment by jkeck** [comment]
@anarchivist happy to work w/ you on
> Crib remaining ArcLight config files from existing arclight-demo app or w/ @anarchivist's input

Otherwise, the other tasks in this ticket are complete.

**Comment by anarchivist** [comment]
@jkeck Cool - let's touch base Monday.
