### ISSUE TITLE
Stanford theme: Header and search bar

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/stanford-arclight#108]
Split out of #91 

## Header and search bar

- [x] Start with base styles from My Library Account for body, headings, `<a>` and colour variables.
- [x] Replace Arclight logo w SUL logo; link to library.stanford.edu
- [x] Move Bookmarks from topbar to al-masthead
- [x] Suppress the History link
- [x] ~Add icons to al-masthead links~ 👉 #114
- [x] Style header area as in My Library Account

<img width="1144" alt="header and search bar" src="https://user-images.githubusercontent.com/6945691/67443401-90e21000-f5b9-11e9-95bb-3dca62be7380.png">

**Comment by jkeck** [comment]
Closed by #113
