### ISSUE TITLE
Add content to index

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/stanford-arclight#146]
#105 updates us to latest version of ArcLight. We will need to reindex all of the content into a new index.

@anarchivist are those EADs needing to be indexed somewhere handy?

**Comment by anarchivist** [comment]
Yup - details are in [this wiki page](https://github.com/sul-dlss/stanford-arclight/wiki/How-to-index). The files are in another Github repo ([sul-dlss/stanford-arclight-test-data](https://github.com/sul-dlss/stanford-arclight-test-data)).

**Comment by mejackreed** [comment]
TY!

**Comment by mejackreed** [comment]
Now all indexed into demo and prod.
