### ISSUE TITLE
Look into indexing errors

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/stanford-arclight#148]
Although content from https://github.com/sul-dlss/stanford-arclight-test-data was successfully indexed, there were some errors from the following:

 - ars
 - hoover
   - several to look at but pamphcol.xml was particularly troublesome

Look into these.

**Comment by marlo-longley** [comment]
Closing - we think ARS stuff is mostly handled and Hoover does not have their content in Aspace. 
If issues arise we can open new tickets.
