### ISSUE TITLE
Ensure application is limited to campus only 

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/stanford-arclight#2]
This is only a test application, so it should be limited to campus only use. We don't want to require anyone to log in to see it, since stakeholders may want to demonstrate it an on-site researcher.

**Comment by mejackreed** [comment]
Confirmed that `sul-arclight-demo` and `sul-arclight-dev` are not available off campus without VPN access.

@anarchivist anything else that needs to be done here? Please reopen if so.

**Comment by jkeck** [comment]
@mejackreed what about sul-arclight-prod?

**Comment by mejackreed** [comment]
Ah nice catch. I'm unable to access `sul-arclight-prod` off campus without the VPN. So I think we are 👌
