### ISSUE TITLE
Remove dependency on ruby-sass which has reached end of life

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#290]
ruby-sass has reached end of life, see:

- https://github.com/sass/ruby-sass
- https://sass-lang.com/blog/ruby-sass-is-unsupported

This project still depends on sass-rails 5.1.0 which depends on ruby-sass: https://github.com/sul-dlss/stanford-arclight/blob/master/Gemfile.lock#L356

**Comment by jcoyne** [comment]
This is blocked by dependency on the bootstrap gem. which requires sassc (libsass), which is also deprecated https://sass-lang.com/blog/libsass-is-deprecated

**Comment by corylown** [comment]
If we start over with a new rails app this can be closed: #310
