### ISSUE TITLE
Ensure @anarchivist can get in and kickoff indexing jobs

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/stanford-arclight#3]
Since the test phase is not being resourced as a dev cycle, I'll need to be able to get in and index finding aids myself.

* [x] Ensure @anarchivist has adequate permissions to log in to `sul-arclight-prod`
  * sul-dlss/puppet#3135
* [x] Ensure @anarchivist can start an indexing job
* [x] Write any (brief) documentation as needed

**Comment by jkeck** [comment]
@anarchivist do you know where the EAD that you'll be indexing will be/live?  Is the expectation that it'll be fetched from stacks or are you planning on having them located physically on the server?

**Comment by anarchivist** [comment]
Right now the files are in in a Google Drive folder - I'd imagined that the contents of that folder would be copied to a server. They could also live in a separate Git repo somewhere if that made sense.

**Comment by jkeck** [comment]
https://github.com/sul-dlss/arclight/wiki/Indexing-EAD-in-ArcLight is the main documentation for how to index things into Arclight.  When we touch base on Monday we can look at what your local workflow will be and can document what needs to be done for Stanford Arclight.
