### ISSUE TITLE
What to do about exported EADs that do not have an ead id?

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#357]
Some resources have an empty eadid field in the exported EAD file.

**ARS**

Published:
/repositories/11/resources/10588
/repositories/11/resources/11173
/repositories/11/resources/10770
/repositories/11/resources/10826
/repositories/11/resources/8601
/repositories/11/resources/12116
/repositories/11/resources/7250
/repositories/11/resources/8033
/repositories/11/resources/9181
/repositories/11/resources/9423
/repositories/11/resources/13209
/repositories/11/resources/10904

Unpublished:
There are 108 unpublished resources without an EAD ID. Not going to list them all here.

**SPEC/UA**

Published:
/repositories/2/resources/7009
/repositories/2/resources/11026
/repositories/2/resources/11591
/repositories/2/resources/1965
/repositories/2/resources/13356
/repositories/2/resources/11029
/repositories/2/resources/12425
/repositories/2/resources/11102
/repositories/2/resources/7008
/repositories/2/resources/12111
/repositories/2/resources/8222
/repositories/2/resources/7006
/repositories/2/resources/7007
/repositories/2/resources/7781
/repositories/2/resources/12884
/repositories/2/resources/12887
/repositories/2/resources/12911
/repositories/2/resources/1847
/repositories/2/resources/11030
/repositories/2/resources/12741
/repositories/2/resources/12722
/repositories/2/resources/13579

Unpublished:
There are 4,711 unpublished resources missing an EAD ID. I'm not going to list them all here.

**Medical History Center**

Published:
/repositories/16/resources/13171
/repositories/16/resources/13123
/repositories/16/resources/13294

**Stanford Law School**

Published
/repositories/17/resources/10239
/repositories/17/resources/10325

Unpublished:
/repositories/17/resources/10214
/repositories/17/resources/10407
/repositories/17/resources/9408
/repositories/17/resources/10291
/repositories/17/resources/10241
/repositories/17/resources/9645
/repositories/17/resources/9409
/repositories/17/resources/10240
/repositories/17/resources/10238
/repositories/17/resources/10292
/repositories/17/resources/9431
/repositories/17/resources/9513
/repositories/17/resources/9517
/repositories/17/resources/9518
/repositories/17/resources/9540
/repositories/17/resources/10250
/repositories/17/resources/10243
/repositories/17/resources/10406
/repositories/17/resources/9413
/repositories/17/resources/9690
/repositories/17/resources/10260
/repositories/17/resources/9632
/repositories/17/resources/9449
/repositories/17/resources/11408
/repositories/17/resources/9658
/repositories/17/resources/9512
/repositories/17/resources/10242
/repositories/17/resources/10245
/repositories/17/resources/13041
/repositories/17/resources/10719

**East Asia Library**

Unpublished:
/repositories/15/resources/10415
/repositories/15/resources/12989

**Music Library:**

Unpublished:
/repositories/12/resources/7303
/repositories/12/resources/7305
/repositories/12/resources/7306
/repositories/12/resources/9905

**Comment by marlo-longley** [comment]
EAD IDs must exist. Data must be remediated.
Analysis here: https://docs.google.com/spreadsheets/d/1n-uoP9_P4SukHN__s7W2J3A9carmr9oJmb9Ydiqy2lE/edit#gid=397826237
