### ISSUE TITLE
Address data issue where children of a collection are also marked as collections in aspace

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#361]
I'm not sure if the problem is that ArcLight is making incorrect assumptions that collections are top level resources with an ead id or if some of our records in ASpace need review/remediation.

If you look at these resources in ASpace you'll see that some of the children are labeled as collections. This does not prevent indexing but causes an error in the application when viewing these records in results lists.

The following collections have this issue:

**Special Collections**

- SC1138
- SCM0440

**Cubberley**

- Cubb00342
- Cubb00491
- Cubb00939
- Cubb00999
- Cubb01116
- Cubb01144
- Cubb01553
- Cubb01726
- Cubb01755

A couple of examples of what this looks like in ASpace:

![Image](https://github.com/sul-dlss/stanford-arclight/assets/458247/cdf15b95-a727-4284-887a-586f450aec2a)

![Image](https://github.com/sul-dlss/stanford-arclight/assets/458247/4d935b4a-740c-4031-8101-21bc9a1958ad)

**Comment by dinahhandel** [comment]
I think we can address this with archivists directly, it is a relatively small number of collections, and Cubberly is somewhat of an outlier as well. I will reach out separately.

**Comment by dinahhandel** [comment]
UA has plans to address the two collections this shows up in.

**Comment by dinahhandel** [comment]
Cubberley has also resolved this issue.
