### ISSUE TITLE
Add redis & sidekiq so we can handle indexing tasks in background jobs

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#364]
I think we're going to want to add redis to stanford-arclight puppet configs so we can add sidekiq to the project and use it to queue up indexing jobs to run in the background.

**Comment by marlo-longley** [comment]
Do we want to install redis on the same VM locally, or on a solo server?

**Comment by marlo-longley** [comment]
See https://github.com/sul-dlss/puppet/pull/10076/files

**Comment by marlo-longley** [comment]
Now see https://github.com/sul-dlss/operations-tasks/issues/3542

**Comment by marlo-longley** [comment]
Robert says he has added redis and sidekiq to arclight-demo. We should test out some indexing and then approve him to apply the same settings to arclight-prod in the ops-task ticket.
