### ISSUE TITLE
Evaluate whether we need to support a more manual EAD upload/indexing process that archivists can control

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#366]

**Comment by dinahhandel** [comment]
Based on conversations during our in-person meetings, the ability to manually export EAD and publish to ArcLight is an expectation among archivists. Given the significant discrepancy (even more so than expected) between published collection finding aids in ArchivesSpace and what has been exported and published to OAC, I am anticipating this will be requested by archivists and may need to be utilized as an interim solution to populate ArcLight while collection remediation work takes place.

**Comment by corylown** [comment]
If we're going to support a manual workflow in addition to an automated one we'll need a way to prevent these manually added records from being deleted or overwritten by automated processes. I could also see it becoming confusing to have some records that update automatically and other that don't.

**Comment by dinahhandel** [comment]
Very true. I think we may have to say our workflow will be entirely manual until a certain point (remediation is completed by special collections staff). Is that feasible? I expect that archivists will not be able to address the remediation needs for some time, but we can find out more when we meet with them.

**Comment by marlo-longley** [comment]
The answer to this question is no, pending success with Cory's "one time sync up" proposal.

**Comment by marlo-longley** [comment]
Update: Archivists are supportive of the one-time sync up, followed by ongoing manual remediation when they are working on a particular EAD in the future.
