### ISSUE TITLE
clicking on indexed terms does not work

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#370]
Click on Women's studies. in https://sul-arclight-demo.stanford.edu/catalog/sc0673-xml just takes the user to a list of all items.

**Comment by marlo-longley** [comment]
This will be fixed in Core by https://github.com/projectblacklight/arclight/pull/1441

**Comment by corylown** [comment]
This was fixed up updating Arclight to v1.1.0
