### ISSUE TITLE
What is the logic of ordering collections on the repository page

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#371]
It seems to be different each time I click back to it: https://sul-arclight-demo.stanford.edu/repositories/speccoll. I'm guessing it should be alphabetical as it is https://sul-arclight-demo.stanford.edu/catalog?f%5Blevel%5D%5B%5D=Collection&f%5Brepository%5D%5B%5D=Special+Collections.

**Comment by corylown** [comment]
Duplicates https://github.com/sul-dlss/stanford-arclight/issues/429
