### ISSUE TITLE
 Let capistrano manage/restart sidekiq on deploys

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/stanford-arclight#387]
For an example see https://github.com/sul-dlss/dlme/blob/a2ddfdff2d520f69b8450074d34238dd437eebfa/config/deploy.rb#L46 ?

**Comment by corylown** [comment]
Looks like we do this differently in other apps, see: https://github.com/pod4lib/aggregator/blob/90fb16586093b4fbc51fabd35bb88229fc048dbb/config/deploy.rb#L56

**Comment by corylown** [comment]
I think some additional puppet config is needed to grant capistrano sudo permission to manage sidekiq.

**Comment by corylown** [comment]
I think this will do it: https://github.com/sul-dlss/puppet/pull/10133

**Comment by corylown** [comment]
Completed via https://github.com/sul-dlss/puppet/pull/10133
