### ISSUE TITLE
Limit access to the /sidekiq route

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/stanford-arclight#388]
Since we don't have users in this application we will need a different approach.

**Comment by corylown** [comment]
Looks like we can handle this via a puppet config if we don't otherwise need to support login in the app:

Something like what we have set up for content_search: https://github.com/search?q=repo%3Asul-dlss%2Fpuppet+path%3A+%27%2Fsidekiq%27&type=code

**Comment by corylown** [comment]
Added a comment about this to https://github.com/sul-dlss/operations-tasks/issues/3542

**Comment by corylown** [comment]
Completed via https://github.com/sul-dlss/puppet/pull/10130
