### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/stanford-arclight#396]
Out of the box configuration is fine for now.

**Comment by marlo-longley** [comment]
I thought this was standard/semi-requierd practice for our Access Team apps but it may not be needed. Closing until we get a specific PO request for this feature (:

**Comment by corylown** [comment]
@marlo-longley I'm going to re-open this because I think there's an expectation that all our apps are tracked in GA.

**Comment by jcoyne** [comment]
@corylown Can we validate that this is still a need and not just dogma? Who needs this and to what end?

**Comment by marlo-longley** [comment]
We have confirmed with Dinah that we will want this when we go to production. This is not a priority until that time.
