### ISSUE TITLE
sul-arclight-* VMs are under-resourced when processing batches of larger finding aids

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#402]
Observed request time-outs when running a set of jobs to download and index everything published in aspace. Some of the finding aids are 10MB+. We will likely need more resourcing on a dedicated worker VM in a production environment.

We might want to consider a load balanced situation: sul-arclight-prod-a, sul-arclight-prod-b, sul-arclight-worker-a, sul-arclight-worker-b. sul-arclight-stage-a, sul-arclight-stage-b, sul-arclight-worker-a, sul-arclight-worker-b. Redirect sul-arclight-demo to sul-arclight-stage or prod.

Other considerations: separate redis/db instances? attached storage for EAD files (the full set of records is likely to be quite large)? The processing is quite bursty, most of the time nothing is happening and we process a handful of updated records per day, sometimes we need to process everything and the demand/load on the VM is quite high. If we don't mind this occasional use being slow maybe we get away with a single work VM?

For storage for finding aids on the VMs: all the finding aids on OAC amount to 516 MB

**Comment by corylown** [comment]
# Currently considering:

The demand for processing large numbers of EADs should be so infrequent that I'm not sure having separate worker VMs is justified unless we need to process everything as fast as possible for some reason.

## Prod
`sul-arclight-prod-a` 8GB, sidekiq 3 threads
`sul-arclight-prod-b` 8GB, sidekiq 3 threads
`sul-arclight-db-prod-a`
`sul-arclight-db-prod-b`
`sul-arclight-redis-prod-a`
2GB shared storage mounted on `sul-arclight-prod-a/b` at `/opt/app/sul-arclight/datashare`

`SIDEKIQ_REDIS_URL: 'redis://sul-arclight-redis-prod-a.stanford.edu:6379/0'`
`CACHE_REDIS_URL: 'redis://sulr-arclight-redis-prod-a.stanford.edu:6379/1'`

## Stage
`sul-arclight-stage-a` 8GB, sidekiq 3 threads
`sul-arclight-stage-b` 8GB, sidekiq 3 threads
`sul-arclight-db-stage-a`
`sul-arclight-db-stage-b`
`sul-arclight-redis-stage-a`
2GB shared storage mounted on `sul-arclight-stage-a/b` at `/opt/app/sul-arclight/datashare`

`SIDEKIQ_REDIS_URL: 'redis://sul-arclight-redis-stage-a.stanford.edu:6379/0'`
`CACHE_REDIS_URL: 'redis://sulr-arclight-redis-stage-a.stanford.edu:6379/1'`

**Comment by taylor-steve** [comment]
This looks great to me

**Comment by taylor-steve** [comment]
Now that we're considering storing PDFs local to the app in #435, I think we should consider increasing the size of the shared storage. Maybe to 5-10GB?

I created 2556 PDFs from as many EADs I had laying around, for a total size of 337 MB.

It's hard to get a feel for the average size.
- Smaller EADs (e.g., 5-10KB) turn into a baseline size of PDF around 60-70KB.
- Larger EADs (e.g., 830KB) sometimes they turn into smaller PDFs (689KB in this case)
- There are a few outliers that are 1-3MB.

**Comment by corylown** [comment]
All the PDFs & EAD files from OAC and ASpace use up 1.3 GB.
