### ISSUE TITLE
Use final/approved images for each repository on landing page

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#418]
https://sul-arclight-demo.stanford.edu/ each repository requires a new image that is not broken.

**Comment by dinahhandel** [comment]
Prefer to have images that we add to the app so they are stable. Need guidelines on appropriate aspect ratio etc. What do archivists want?

**Comment by marlo-longley** [comment]
Fixed by #469

**Comment by marlo-longley** [comment]
Sorry; re-opening. I fixed this so we didn't have to look at broken images daily, but the question of which to use is a design/stakeholder issue. Just let us know the images and we can swap them out.

**Comment by marlo-longley** [comment]
I believe this is closed by #579
