### ISSUE TITLE
Load missing finding aids using OAC as a reference

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#424]
Arclight@SUL is currently populated with published finding aids the published components of those finding aids. This is only a subset of all the finding aids that are published to OAC.

OAC page listing the stanford repositories held by OAC: http://voro.cdlib.org/oac-ead/prime2002/stanford/
OAC landing page: https://oac.cdlib.org/

In the fall of 2023 we assembled an inventory of the finding aids in OAC whether they are published or not in ArchivesSpace. Inventory here: https://docs.google.com/spreadsheets/d/1n-uoP9_P4SukHN__s7W2J3A9carmr9oJmb9Ydiqy2lE/edit?usp=sharing

Here's an updated inventory completed on March 22, 2024: https://docs.google.com/spreadsheets/d/1N2L6FInoFXo23-_HQNsSDK5BPTOuPw5q0cqUhc8JESA/edit#gid=347016939

We need to find a way to ingest the set of finding aids that are published to OAC but are not published in ArchiveSpace while also ensuring that we do not publish components of those finding aids that are not meant to be public.

There are two possible options:

1. For the set of finding aids that are published to OAC but are unpublished in ArchiveSpace, determing whether we can compare the finding aids at the component level so we know what should be published to Arclight@SUL. If we're able to do this, use the ArchiveSpace API to do a one-time ingest of these finding aids and the correct set of components to ArcLight@SUL.
2. If the first option is not successful, determine whether we can use the EAD files held by OAC for ingest into ArcLight@SUL. This would only be for the set of finding aids that are published to OAC but are unpublished in ArchiveSpace.

**Comment by corylown** [comment]
# OAC => ASpace => ArcLight Repository Mappings

| OAC Repository | ArchivesSpace Repository | ArcLight Repository  |
|--------|--------|--------|
| cstmus | ARS | ars |
| cstmusl | ARS | ars |
| cstl | MHC | ? |
| mss | SPECCOLL | manuscripts |
| rbd | SPECCOLL | manuscripts | 
| uarc | SPECCOLL | uarc |

**Comment by corylown** [comment]
Based on our investigations of Plans A and B as well as discussion with Archivists we will:

Load the following repositories from OAC in a one-time sync up:
SPECCOLL (Manuscripts, University Archives)
EAL

Configure the following repositories to add/update/delete from ASpace:

ARS
Cubberley
MHC?

**Comment by dinahhandel** [comment]
Rare Books Division should use EAD from OAC for the ArcLight beta application. However, two finding aids will need to be manually removed: Antiquarian Map Collection and Norwich (Oscar I.) African Map collection (now stewarded part of the David Rumsey Map Collection).
