### ISSUE TITLE
Apply Stanford-specific branding

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#425]
Stanford color palette (although beige is not a good option in the facets) that adheres to accessibility contrast requirements

**Comment by corylown** [comment]
Current Figma designs: https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=6-85&t=ndOaRifJfhSSLenN-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=6%3A85&show-proto-sidebar=1

**Comment by cbeer** [comment]
fwiw, we've done a pretty accurate bootstrap 5-flavored stanford footer in sul-requests: https://github.com/sul-dlss/sul-requests/pull/2074

**Comment by corylown** [comment]
Closing in favor of:

#428 
#566 
#567 
#565
