### ISSUE TITLE
Determine public URL for production site

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#426]
URL: [archives.stanford.edu?](http://archives.stanford.edu/?) [findingaids.stanford.edu?](http://findingaids.stanford.edu/?)

Project team doesn't want to use archives.stanford.edu because technically University Archives is considered "Archives" and other options are: [inventories.stanford.edu](http://inventories.stanford.edu/) 
[guides.stanford.edu](http://guides.stanford.edu/) [context.stanford.edu](http://context.stanford.edu/). This is a challenging requirement because most other institutions use archives or findingaids.

**Comment by dinahhandel** [comment]
As of now, we are going with archives.stanford.edu.

**Comment by corylown** [comment]
Part of https://github.com/sul-dlss/operations-tasks/issues/3744
