### ISSUE TITLE
Landing page design

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#427]
Landing page for ArcLight at SUL that includes: search bar with obvious option for advanced search, information on which collections/repositories are in ArcLight and the option to go to the collection list page for each of those repositories, feedback option, and content warning/link to email and more information, request info/Aeon. Would be nice to have dynamic count of collections and images displayed like Duke/Michigan.

https://findingaids.princeton.edu/ but lacks the ability to build an advanced search. https://findingaids.lib.umich.edu/ has advanced search but missing other details about request/feedback/contact, https://archives.lib.duke.edu/ has advanced search, ask for help, and describes what finding aids are.

**Comment by corylown** [comment]
Current Figma Designs: https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=6-85&t=ndOaRifJfhSSLenN-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=6%3A85&show-proto-sidebar=1

**Comment by dinahhandel** [comment]
Here's everything that will be on the landing page: 

Search bar 
Advanced search - link
Browse all collections - link
Browse all repositories  - link
Images of digital content found in finding aids (list of purls needed)
Contact us link (where does this email go to? Specific arclight-feedback list?)
How to use this site (text needed)
Location (the issue with this is that there are multiple locations and hours. Princeton does a nice job of showing two locations and hours, could we do the same for all locations or is that too busy?)

- Show all locations and just display hours, link to location’s page on the website 

Request materials (text needed for signing up for account, Princeton has nice example)
Ask a librarian (linked to: https://library.stanford.edu/research-support/subject-specialists) 
Content warning

- Icon

- Some materials and descriptions may include offensive content. __ex:_ [More_ info](https://library.duke.edu/about/statement-potentially-harmful-language-library-descriptions)

Beta instance banner (text needed)
Feedback 
SearchWorks footer

@astridu will be adding the link to the Figma designs when they are completed. @corylown for the portions of the design where text or links are needed, should I put that in this ticket? Or do you prefer that it go into the Figma design document?

**Comment by corylown** [comment]
@dinahhandel my guess is it's easier for everyone to put that info in the ticket, but either works.

**Comment by dinahhandel** [comment]
**About This Site**
Use this portal to search and explore finding aids, also called collection guides. Search across all finding aids by keyword, subject, title, or browse by contributing repositories. 

Finding aids describe collections of primary sources and other unique, original, or rare materials held across the special collections repositories at Stanford Libraries. Materials may include manuscript collections, organizational records, photograph collections, ephemera, and born-digital materials. Some digitized archival materials may be present within finding aids, and digital collections may be found in [SearchWorks](https://searchworks.stanford.edu/).

The finding aid provides information about:
The origin of the collection
A brief biography or historical sketch of the individual or organization that created the collection
A statement of the intellectual and physical organization of the collections
A narrative "scope and content note" describing the intellectual content of the collection as a whole and of its major subdivisions
A detailed "contents list" providing a hierarchical listing of the collections from the series down to the file, or possibly the item, level

**Comment by dinahhandel** [comment]
**Request Materials**
Stanford University Libraries acquires, preserves, and makes available materials of enduring historic value to support the research needs of Stanford students and faculty and the larger scholarly community. Rare and distinctive materials exist in several locations across Stanford University Libraries. Click the Request button below to learn more. 

Request button = https://library.stanford.edu/access-rare-and-distinctive-materials

**Comment by dinahhandel** [comment]
**Ask a Librarian**
Have questions about Stanford University Libraries collections or accessing materials? Contact a librarian for help. 

Contact us = https://library.stanford.edu/research-support/subject-specialists

**Comment by dinahhandel** [comment]
**Some materials and description may contain offensive content.** 
More info = https://library.stanford.edu/libraries/special-collections

**Comment by dinahhandel** [comment]
alt text for images in the PURL display on the landing page should be from the title and collection of the image.

**Comment by taylor-steve** [comment]
@astridu The two blue links on white background ("SearchWorks" and "More info") are getting flagged by lighthouse as having low contrast. I'm currently getting around this by bumping up the font-weight from 400 to 450 for blue links. Let me know if there's something else you'd prefer to try. I have already tried the slightly darker blue at normal font-weight and that also had insufficient contract.

**Comment by astridu** [comment]
@taylor-steve That is strange. That is Stanford's digital blue (from identity guide) which we use for links. It's this blue right? 006CB8
I checked it on WebAIM, and it says it passes AA and AAA.

**Comment by taylor-steve** [comment]
@astridu Yes that's the blue. I guess lighthouse doesn't know everything!

**Comment by taylor-steve** [comment]
@dinahhandel for 'Green Library, 2nd Floor' do you know specifically which location we should be pulling the hours from? I assumed it was special collections because the hours matched what was shown in the design, but after talking with @corylown I figured I better ask.

**Comment by dinahhandel** [comment]
@taylor-steve yes, the special collections reading room.
