### ISSUE TITLE
Repositories page design

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#428]
[Page of repositories ](https://sul-arclight-demo.stanford.edu/repositories)should be separate from landing page, is a list the best format? 

Other institutions have done cards/3 per row, example: https://findingaids.lib.umich.edu/repositories

**Comment by corylown** [comment]
Current Figma designs: https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=8-23&t=ndOaRifJfhSSLenN-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=6%3A85&show-proto-sidebar=1

**Comment by astridu** [comment]
<img width="332" alt="ars" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/939b4b5a-f338-47ab-badb-efd6a554dc29">
<img width="333" alt="cubberley" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/9fc60f89-5402-4076-96d8-96a6bf2f660f">
<img width="326" alt="eal" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/363f62c5-86f1-40f7-8a82-39d867976e8c">
![manuscripts](https://github.com/sul-dlss/stanford-arclight/assets/42216982/997c4a52-b0d9-4845-b4b3-e59f4d1fb0ae)
![med](https://github.com/sul-dlss/stanford-arclight/assets/42216982/d5d29ed2-99b2-48f4-a8df-3146ce8dea44)
![rarebooks](https://github.com/sul-dlss/stanford-arclight/assets/42216982/6836724a-4d53-4725-afb1-932b1852b209)
![ua](https://github.com/sul-dlss/stanford-arclight/assets/42216982/ff4cbbc2-6cb5-466b-acbe-7e119d225f89)

**Comment by astridu** [comment]
![ua](https://github.com/sul-dlss/stanford-arclight/assets/42216982/3d90f122-6a9c-44d6-ad92-872c74abc5b6)

**Comment by marlo-longley** [comment]
Hi @astridu these look great, thanks.

Question about the design, the bottom card that spans the whole row for University Archives. Is this specifically for UA, or is it just because it is a lone card on its own row? In the design there is a neat number of other repositories, 6 which makes for 2 neat rows -- how would I handle 5 or 7 repositories? In that case would UA still have its own full-width row?

**Comment by astridu** [comment]
Good question! If UA asks, then yes, it's specifically for UA to give them the presence they deserve :) But in the case of uneven number of cards, it is for the odd card out, we'd give them the whole row as a consolation prize since they didn't fit neatly in a row.

**Comment by marlo-longley** [comment]
Thanks! If there are 2 cards in a row, how would that work?

**Comment by astridu** [comment]
For 5 cards, we can either do 2x2x1: https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?page-id=0%3A1&type=design&node-id=471-190&viewport=-9127%2C153%2C1&t=HmJjEnWAypmxUpea-1&scaling=min-zoom&starting-point-node-id=471%3A190&show-proto-sidebar=1&mode=design

Or what might be easier and scalable is 3x2 (with the second row centered): https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?page-id=0%3A1&type=design&node-id=472-264&viewport=-9127%2C153%2C1&t=HmJjEnWAypmxUpea-1&scaling=min-zoom&starting-point-node-id=472%3A264&show-proto-sidebar=1&mode=design

So then if there is 1 card, we stretch it across, if there are 2 cards in the last row, we center them. What do you think?

**Comment by marlo-longley** [comment]
@astridu thanks! Either is doable honestly, but I can go with the second approach for now. If you feel strongly about using the first approach though let me know.

**Comment by astridu** [comment]
Second approach works for me. Thank you!

**Comment by marlo-longley** [comment]
Thanks @astridu -
I was starting to use a shared style for these cards from the landing page, and I noticed the buttons are different widths on the different page designs. Is this intentional, and is one preferred? I will say that the wider/full-width buttons are slightly easier to style.

**Comment by marlo-longley** [comment]
![Image](https://github.com/sul-dlss/stanford-arclight/assets/1328900/df20ae56-6c3c-4e80-a53b-310d2d96d864)
![Image](https://github.com/sul-dlss/stanford-arclight/assets/1328900/21cbad61-8958-4f12-9360-b0bd0f6c1dae)

**Comment by astridu** [comment]
@marlo-longley Yes, we can do the wider buttons as the style on all the cards. I agree it also looks better. Thank you!

**Comment by marlo-longley** [comment]
Hi @astridu -- I am getting an error from GH when trying to download these thumbnail images ("This private-user-images.githubusercontent.com page can’t be found").

I was able to download the ones you put in the Figma design: https://www.figma.com/file/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=10-213&mode=design&t=q4vXpdvyxFY2TXT9-0

But there are a few (for ARS, Cubberly) not present in the design that I wasn't able to get. Is it possible to add those to Figma, or send them to me another way? Thank you.

**Comment by astridu** [comment]
@marlo-longley I am attaching the files here. Let me know if this works.

<img width="332" alt="ars" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/18479e5d-e7e8-4e11-b2c3-e26511773ad5">
<img width="333" alt="cubberley" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/d5ad762b-d3c8-4a41-aad2-808185c29d63">

**Comment by astridu** [comment]
I also sent them via slack if this doesn't work.

**Comment by marlo-longley** [comment]
Got em -- that works for whatever reason! Thanks for the quick reply!
