### ISSUE TITLE
List of collections on repository page should be in alphabetical order by collection name

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#429]
When you click on a repository to view their collections, collections should be displayed in alphabetic order by collection name.

Not clear what the display order is now, it isn't collection ID either.

**Comment by taylor-steve** [comment]
This appears to be controlled, by omission, in Arclight:

https://github.com/projectblacklight/arclight/blob/54bfcb3b44afd98768bc24e131536e5ba968c15d/app/controllers/arclight/repositories_controller.rb#L14

As far as I can tell, that doesn't merge in any blacklight config options that would help us.

Given that I'd say our options are:
* Add the sort globally in Arclight
* Override the behavior locally
* Add some sort of config to control sort (hopefully there's some sort of Blacklight convention for this?)

Any opinions on these/anything I missed?

**Comment by corylown** [comment]
Another option would be to link from the repositories page directly to a search results page that sorts alphabetically and has the added bonus of being a fully feature search interface.

https://sul-arclight-demo.stanford.edu/catalog?f%5Blevel%5D%5B%5D=Collection&f%5Brepository%5D%5B%5D=Archive+of+Recorded+Sound

Maybe a question for @dinahhandel

**Comment by corylown** [comment]
Decision: from the repositories page we will link directly to a search result for the collections in the repository and bypass the list of collections page.

**Comment by marlo-longley** [comment]
Be sure to make both the Title text ("Archive of Recorded Sound") and the gray View More button both link to the same, new, location.
