### ISSUE TITLE
Display visit, request, and cite information at the collection level

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#433]
Michigan does this with a right-side box that reads "Using these materials" and also contains collection-level restrictions. Duke does this with a similar layout.

https://findingaids.lib.umich.edu/catalog/umich-bhl-8782
https://archives.lib.duke.edu/catalog/mississippisummerprojectoralhistories 

This is included in the collection page design in Figma, but I'm not sure we know where the links should go?

https://www.figma.com/file/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=6-122&mode=design&t=CQrvmQEIqemAMLsw-0

**Comment by dinahhandel** [comment]
Info for visitors: https://library.stanford.edu/libraries-0/branches-and-centers 

- I forgot if we discussed whether it was possible to customize per repository. If so: 
- ARS: https://library.stanford.edu/libraries/archive-recorded-sound 
- MSS and UA: https://library.stanford.edu/libraries/special-collections
- EAL: https://library.stanford.edu/libraries/east-asia-library 
- Cubberley: https://library.stanford.edu/libraries/cubberley-education-library 
- Rare Books: https://library.stanford.edu/libraries/special-collections

How to request: https://library.stanford.edu/access-rare-and-distinctive-materials 
- this doesn't take into account that Cubberley doesn't use Aeon, but that's OK for now.

Remove "Ordering reproductions" 

Access and Use jumps to access and use section of the finding aid
