### ISSUE TITLE
Add ability to download finding aid as accessible PDF

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#435]
Note that downloadable PDF must be accessible and need to test output from ArchivesSpace. We have links to do this but they don't work in the demo

**Comment by dinahhandel** [comment]
Relevant slack thread from Archivists working with archival data: https://shoes-untied.slack.com/archives/C120EM598/p1706121812220229

**Comment by marlo-longley** [comment]
Here is a PDF exported from ArchivesSpace

[job_5390_file_5392.pdf](https://github.com/sul-dlss/stanford-arclight/files/14656271/job_5390_file_5392.pdf)

**Comment by marlo-longley** [comment]
Is testing several representative PDFs "Good Enough" to declare PDFs accessible? Or will we test every single PDF that we make available?

**Comment by corylown** [comment]
From Alan via Slack:

> Alan Lundgard
  [5:06 PM](https://stanfordlib.slack.com/archives/C31393CH0/p1711487170025659)
Hi folks, here's a Drive folder containing files related to PDF accessibility testing for ArcLight.
https://drive.google.com/drive/folders/1sFhsczWf_sR3B3Z9e-fPXojUuXPZTJ6P?usp=share_link
The root folder has the original test PDF job_5390_file_5392.pdf and the accessibility report generated by Acrobat job_5390_file_5392.pdf.accreport.pdf (Passed 11 tests, Failed 17 tests). This report breaks down each test, and has links to resources for how to remediate.
The ABBYY Output folder has the result of running the test PDF through ABBYY OCR job_5390_file_5392-abbyy-output.pdf and the accessibility report generated by Acrobat job_5390_file_5392-abbyy-output.pdf.accreport.pdf (Passed 27 tests, Failed 2 tests). There are other ABBYY-related files here, which can be ignored for now.
Hope this is helpful!

**Comment by dinahhandel** [comment]
So if I understand the results of this testing correctly, the PDF that was further processed via ABBYY was more accessible than the PDF that is currently available for download? @alundgard

**Comment by alundgard** [comment]
Sorry, I'm just seeing this. Yes that is correct @dinahhandel

**Comment by dinahhandel** [comment]
@corylown I'm not sure how difficult it would be to hook into our OCR processes to meet this requirement. If you want to learn more, I'm happy to set up a time to talk with the appropriate people. I'm also going to follow up with Mark Custer from Yale about his original post re: PDF accessibility. It sounds like they are using everyone's favorite XSLT to do any transformation from the ASpace EAD to PDF/UA... :)

**Comment by corylown** [comment]
@dinahhandel I think we should pursue the ASpace EAD => XSLT => accessible PDF process. If that doesn't seem viable after we learn more we can think about what it would take to connect with our OCR process, but it sounds tricky on the surface.

**Comment by dinahhandel** [comment]
Here's what was shared from Yale: https://github.com/YaleArchivesSpace/EAD3-to-PDF-UA @corylown it uses something I'm not familiar with and might not be straightforward either.

**Comment by taylor-steve** [comment]
@corylown @marlo-longley 

Regarding packaging required third party tooling to generate PDFs in the app, we'd need the following:

### Saxon
I've been using the current release of [Saxon-HE 12](https://github.com/Saxonica/Saxon-HE/tree/main/12). We'd need the entire contents of the [SaxonHE12-4J.zip](https://github.com/Saxonica/Saxon-HE/tree/main/12/Java) and not just the single jar like I had hoped. Saxon HE is licensed under the Mozilla Public License Version 2.0. I believe this is fine, see Q7 in the [FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ). We might have to link to their GitHub to fully satisfy section 3.2(a), as their included license/documentation doesn't directly mention how to get the source, it only links to their homepage.

### Apache FOP
Similarly, we'd want to bundle [Apache FOP 2.9](https://xmlgraphics.apache.org/fop/) which is licensed under Apache License Version 2.0. I think we'd be good here, see section 4 in the license [documentation][https://www.apache.org/licenses/LICENSE-2.0.html]. They already contain the license and notice in the distribution.

### Fonts and modified ASpace XSL
ASpace packages some [fonts](https://github.com/archivesspace/archivesspace/tree/master/stylesheets/fonts) that the current XSL uses. They have an extremely open [license](https://github.com/archivesspace/archivesspace/blob/master/stylesheets/fonts/ReadMe-Kurinto.txt).

We'd also be packaging a modified version of their [as-ead-pdf.xsl](https://github.com/archivesspace/archivesspace/blob/master/stylesheets/as-ead-pdf.xsl) and an unmodified version of [as-helper-functions.xsl](https://github.com/archivesspace/archivesspace/blob/master/stylesheets/as-helper-functions.xsl). I'm less familiar with the Educational Community License, Version 2.0, but at first read it seems like we'd need to leave their attribution comments untouched and state the nature of our modifications.

Thoughts on bundling vs installing locally per server after reading all this? The dream of course is to eventually be all in on ArchivesSpace, in which case all of this goes away except for changing the one XSL file in ArchivesSpace.
