### ISSUE TITLE
Collection-level URLs that are clear and incorporate the name of the collection

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#436]
Example from Duke: https://archives.lib.duke.edu/catalog/mississippisummerprojectoralhistories

We made a [change in ArcLight](https://github.com/projectblacklight/arclight/pull/1532/commits/8d69057f60efd5b8a1a04332ce9ac7c1b2466d17) to make it easier to modify the collection id formation. That just needs to get into an arclight release then we can use it in our app. We might want to also consider cleaning up the ead id with the `parameterize` method to ensure we're not storing ids with spaces or other weird stuff.

**Comment by dinahhandel** [comment]
Might want to prepend with the call number, would be good to know the longest collection name that we have so we can know the character limit.

**Comment by marlo-longley** [comment]
Right now our URLS are something like:
https://sul-arclight-demo.stanford.edu/catalog/EAL0002 (using the EAD ID as the identifier)
