### ISSUE TITLE
Left panel on record view should be static and right hand panel should scroll

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#439]
Lefthand panel (Collection overview and Collection contents) should be static, while the righthand panel (finding aid front matter) is scrollable.

Michigan does this: https://findingaids.lib.umich.edu/catalog/umich-bhl-976

(Should this be added to upstream ArcLight?)

**Comment by taylor-steve** [comment]
I did a super simple version of this in #473. 

Michigan is doing some additional work to have the contents in its own scrolling container within the sidebar. Is that in scope here? I think it looks great but when it swaps from scrolling the left/right, sometimes I find it confusing.

As far as upstream styling is concerned my default position is that upstream should stay as straightforward as possible. Not a strongly held belief in this case, given that it's 7 lines of CSS.

**Comment by taylor-steve** [comment]
Just realized there's upstream history to this: https://github.com/projectblacklight/arclight/issues/1312
