### ISSUE TITLE
Do not display collection-level access and use information on components

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#445]
Components and sub-components do not need to inherit the collection-level Access and Use section

**Comment by corylown** [comment]
@dinahhandel does this mean remove the entire Access & Use section from components or just specific fields?

![Image](https://github.com/sul-dlss/stanford-arclight/assets/458247/d50b8b46-8433-4925-b3cc-bb841e0668e2)

**Comment by dinahhandel** [comment]
I believe the request was for the whole section to be removed, but at the moment I'm having trouble seeing why the display is an issue. Let me review my notes and get back to you. @corylown

**Comment by marlo-longley** [comment]
We decided to close this for now. If it comes up as an issue again we can reconsider.
