### ISSUE TITLE
Verify that appropriate fields are searched when searching within a collection

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#447]
We want a list of the fields that are searched (and maybe relating the fields to what's coming from the EAD). Should we do this in a Google Sheet?
Identify places where we want to make changes.

**Comment by marlo-longley** [comment]
Here is my writeup: https://docs.google.com/spreadsheets/d/1ccN3l3mZD7al-7c21pkaY8yVYa-i_cZ5jDMlMGTQLrk/edit#gid=0

All of this comes directly from Arclight Core, as we inherit their indexing config completely, aside from a custom title normalizer.

In this custom normalizer, we have a clause for adding `[NO TITLE PROVIDED]` if blank. This could impact search results in the case of searching "title" or "provided", in theory.


I will look into adding the findings of the above spreadsheet perhaps to a wiki in AL Core.

**Comment by marlo-longley** [comment]
See https://github.com/projectblacklight/arclight/issues/1524 for discussion on next steps in Core

**Comment by marlo-longley** [comment]
We broke out ticket #500 from this analysis and can close this one.
I also added a link to this spreadsheet [into the ArcLight Core Wiki](https://github.com/projectblacklight/arclight/wiki/Configuring-Solr-and-Search-Relevancy#what-fields-are-being-searched)
