### ISSUE TITLE
Display digital content icon next to collection titles in search results

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#449]

**Comment by dinahhandel** [comment]
Icon for digital content should immediately follow the collection extent, similar to how it displays when looking at collection contents.

**Comment by dinahhandel** [comment]
@astridu no need to make a new ticket for this design

**Comment by astridu** [comment]
Mock up 
<img width="484" alt="image" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/3b54b2f9-53ff-4508-83b8-c41ac1323b79">

**Comment by dinahhandel** [comment]
Also accommodated in #602
