### ISSUE TITLE
Add digital content button to search results

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#450]
Princeton, Duke, and Michigan have all pinned a "digital content" button on their search all/browse page. It makes it a little easier to navigate straight to collections with online content:
https://findingaids.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q= 
https://findingaids.lib.umich.edu/collections
https://archives.lib.duke.edu?f%5Bhas_online_content_ssim%5D%5B%5D=online&f%5Blevel_sim%5D%5B%5D=Collection )

**Comment by dinahhandel** [comment]
This requirement is accommodated in #602
