### ISSUE TITLE
Enable search by call number

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#451]

**Comment by marlo-longley** [comment]
call number == ead id == collection id

This should work in 2 places:
1. dropdown in searchbar of "Identifier" 
2. And from "all fields"

Should we relabel the term "identifier" ?

**Comment by marlo-longley** [comment]
This technically does work in both cases 1 and 2. However, only in the case of an "All fields" search does the identifier become highlighted in the search results. Is this the desired UI?

All fields search for call number:
<img width="1389" alt="Screenshot 2024-03-22 at 12 37 51 PM" src="https://github.com/sul-dlss/stanford-arclight/assets/1328900/4e7a9bf1-5143-4dc3-8bf6-69bc467057c3">

Identifier search for call number:
<img width="1356" alt="Screenshot 2024-03-22 at 12 37 58 PM" src="https://github.com/sul-dlss/stanford-arclight/assets/1328900/cbb4286e-0d46-491c-947a-5e3624fd8115">


Also, what should we change the wording to, if not Identifier? @dinahhandel

**Comment by dinahhandel** [comment]
I'll ask the archivists about the term "identifier" and get back to you @marlo-longley. ArcLight also refers to it as the Collection ID in the "more info" dropdown on the collection page.

Highlighting of the call number upon return of search results is the desired functionality for all fields. Ultimately, the call number should display on the collection page in a more prominent way (https://github.com/sul-dlss/stanford-arclight/issues/443), I believe the designs are forthcoming for that.

**Comment by dinahhandel** [comment]
Based on feedback from archivists, I think we should rename "identifier" to call number in our instance of ArcLight. @marlo-longley let me know if you have questions or if this should be documented in #490 instead.

**Comment by marlo-longley** [comment]
Here's fine! Thanks @dinahhandel

**Comment by marlo-longley** [comment]
Closed by #501
