### ISSUE TITLE
Accessibility review of ArcLight application

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#457]
Once design changes have been made, the application as whole requires an accessibility review.

**Comment by dinahhandel** [comment]
@astridu would it be possible to start on this during the current sprint so that changes can be made in the final sprint of the work cycle? I think we agreed that it would be feasible to do using the Site Improve browser plug-ins, but not in scope to do a full Site Improve review or SODA review at this time.

**Comment by astridu** [comment]
Sure, I'll run it this afternoon.

**Comment by astridu** [comment]
Should I use demo to test?

**Comment by marlo-longley** [comment]
@astridu https://archives.stanford.edu/ is a good URL to test on. Thanks!
