### ISSUE TITLE
Make it easier to delete a finding aid upon request

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#459]
We learned recently that we may need to delete more finding aids than we previously understood. Ideally, we would have an automated process that would poll archivespace for a list of unpublished collections and delete any that are in the ArcLight index. We cannot do this until we can rely on the accuracy of the published/unpublished flag is ASpace. In the meantime, let's make it as convenient for us as possible to delete a finding aid upon request.

**Comment by dinahhandel** [comment]
Note from the PO perspective, this needs a documented process for archivists to follow when requesting deletion.
