### ISSUE TITLE
[Plan A] Investigate whether we can identify and use the ASpace API to publish collections/components

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#482]
Plan A: use ASpace as the single source of truth and use their API to publish the correct elements using data from OAC

See 2024-03-22 storytime for details: https://docs.google.com/document/d/1_e7ACJmDu7m79is-JtOX5KzaoJSP30GBYxHyXUG9cmc/edit#heading=h.s2uu195aq0j2

See https://github.com/sul-dlss/stanford-arclight/issues/424 for additional discusison

**Comment by marlo-longley** [comment]
Here is some rough draft (but functional) python scripting that compares two folders (containing apsace and oac XML) and produces lists of missing (present in oac but not in aspace) and/or unpublished components (components with `audience=internal` in aspace).

**Comment by marlo-longley** [comment]
Closing as we've broken out #553 to its own set of work.
