### ISSUE TITLE
[Plan B] Investigate whether we can successfully index Finding Aids directly from OAC

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#483]
Plan B: directly index the OAC content into ArcLight, update ASpace as components are touched over the next…decades

See 2024-03-22 storytime for details: https://docs.google.com/document/d/1_e7ACJmDu7m79is-JtOX5KzaoJSP30GBYxHyXUG9cmc/edit#heading=h.s2uu195aq0j2

See https://github.com/sul-dlss/stanford-arclight/issues/424 for additional discusison

**Comment by corylown** [comment]
Documentation/Inventory of data issue with OAC finding aids when indexed in ArcLight: https://docs.google.com/spreadsheets/d/1wPW9Gv0P4wjmOJrZEdE5nudgac82tu6J_bVVkEhqJVA/edit?usp=sharing

**Comment by corylown** [comment]
After completing the inventory, I've found that most finding aids from OAC appear to index fine in ArcLight. While not our ideal solution, if we had to we could use OAC as the source for records to index into ArcLight.

The specific problems fall into three categories:

- Finding aids that were not indexed. In all cases the finding aid was missing a value in the eadid element.
  - Possible solutions:
    -  skip these records
    - use a value from a different field as the fallback id
    - remediate the records
- Finding aids where the filename and the eadid do not match. This doesn't impact our ability to index these findings, but it sure is confusing to figure out what the right id is.
  - Possible solutions
    - do nothing
    - remediate the records
- finding aid has components that are assigned the level collection. This is a problem and makes ArcLight very unhappy
  -  skip these records
  - remediate these records so components are not assigned a level of collection

**Comment by corylown** [comment]
Closing this. Notes are here if this is the approach we decide to take for loading records into ArcLight.

**Comment by dinahhandel** [comment]
In the cases where remediation is one possible solution, how would archivists go about that? I'm guessing that remediating in ArchivesSpace wouldn't change the publication status and trigger the automatic update. Would they edit the record in ArchivesSpace and re-export? Edit the EAD file?

**Comment by corylown** [comment]
@dinahhandel it depends on whether we keep the automated publishing from ASpace turned on for published finding aids in ASpace. If the automated process is turned on then remediating in ASpace and publishing the finding aid would be the ideal fix. Otherwise, I guess they'd apply the fix in Aspace, upload the remediated finding aid to OAC and we'd need to be notified somehow to grab the new file from OAC and load it into ArcLight.
