### ISSUE TITLE
[Plan A - sub task] Publish components via API

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/stanford-arclight#489]
We are able to pull out component ids from EAD, such as `aspace_ref16_hv5` or `aspace_77bceedd5703d902e537e31056c74479`, and use them to analyze published vs unpublished content.

The ASpace API provides a publishing endpoint for working with "archival objects": https://archivesspace.github.io/archivesspace/api/?python#publish-an-archival-object-and-all-its-sub-records-and-components

What is the relationship between component IDs and archival objects, and will we be able to trace this path in order to programmatically publish using the API? Is there another connection point to investigate?

Related to #482

**Comment by taylor-steve** [comment]
In ASpace these types of IDs are referred to as `ref_id`. Within ASpace they do not use the `aspace_` prefix to namespace them, so in API calls those examples would be `ref16_hv5` and `77bceedd5703d902e537e31056c74479`. I believe for this work; components and archival objects are the same thing. 

I've been using this to strip the prefix:
```python
def remove_aspace_prefix(id):
    return id.replace("aspace_", "", 1) if id.startswith("aspace_") else id
```

The ASpace API provides an archival object lookup method that can accept `ref_id`:
https://archivesspace.github.io/archivesspace/api/?python#find-archival-objects-by-ref_id-or-component_id

For example:
```python
# Client setup omitted
archival_objects = client.get("/repositories/2/find_by_id/archival_objects", params={"ref_id[]": "ref16_hv5"})
```
yields
```json
{"archival_objects": [{"ref": "/repositories/2/archival_objects/13178"}]}
```

Ready to append `/publish` and post, like your link describes. The same method also provides a way to return the full object should we need to confirm anything prior to publishing:
```python
archival_objects = client.get("/repositories/2/find_by_id/archival_objects", params={"ref_id[]": "ref16_hv5", "resolve[]": "archival_objects"})
```
yields
```json
{"archival_objects": [
  {"ref": "/repositories/2/archival_objects/13178",
   "_resolved": { full object here }
  }
]}
```

You can also search for multiple archival objects at a time:
```python
multiple_refs = {
  "ref_id[0]": "ref16_hv5",
  "ref_id[1]": "77bceedd5703d902e537e31056c74479"
}
archival_objects = client.get("/repositories/2/find_by_id/archival_objects", params=multiple_refs)
```

yields

```json
{"archival_objects": [{"ref": "/repositories/2/archival_objects/1181562"}, {"ref": "/repositories/2/archival_objects/13178"}]}
```

I've done some testing publishing and unpublishing archival objects on stage via the API. It works exactly as I would expect, publishing the object and its children.

One thing about their documentation gives me pause:

> Publish an Archival Object and all its *sub-records* and components.

I'm still trying to find a definitive list of what can be a sub-record and if any of them could cause "spill over" (e.g., if they were some sort of reference type that could point outside the local heirarchy).

**Comment by taylor-steve** [comment]
Follow-up to my sub-record concern. There is a list of sub-record types here in the "Subrecord Tables" section: https://archivesspace.github.io/tech-docs/architecture/backend/database.html

Those types match up with what is returned by this API call:

https://archivesspace.github.io/archivesspace/api/#get-a-list-of-record-types-in-the-graph-of-an-archival-object

Given that list, I have no more concerns. I would expect all of those types to be published as part of publishing an AO.

**Comment by taylor-steve** [comment]
After more testing I want to specifically call out that the `/repositories/:repo_id/archival_objects/:id/publish` endpoint publishes the *entire* subtree (children, grandchildren, great grandchildren, ...).

If we need to publish a single AO without modifying its children, it looks like we can do that by updating the AO itself:

```python
original_ao = client.get("/repositories/2/archival_objects/1282471").json()
new_ao = original_ao
new_ao["publish"] = True
update_ao = client.post("/repositories/2/archival_objects/1282471", json=new_ao)
```

**Comment by marlo-longley** [comment]
Thanks for all this analysis, @taylor-steve  !
