### ISSUE TITLE
Improve Identifier search

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/stanford-arclight#490]
The "Identifier" search combines the Solr fields `id`, `ead_ssi`, `unitid_ssm`, and `ref_ssm` (these fields exist at the collection and component levels, with the exception of `ref_ssm`, which only exists on components).

These fields are all indexed with Arclight Core config. There is minor normalization that occurs on `id`: any periods are replaced with a hyphen: https://github.com/projectblacklight/arclight/blob/d26cd8ff0fed44356987b45751069f069dfac469/lib/arclight/traject/ead2_config.rb#L78

Using collection id ARS.0043 as an example (so `id` is ARS-0043, but `ead_ssi` etc remains as ARS.0043), we have the following search results:
- In an "All fields" search, "ARS-0043" returns the proper result
- In an "All fields" search, "ARS.0043" returns the proper result
- In an "All fields" search, "ARS0043" returns the proper result, via the "text" dump Solr field
- In an "Identifier" search, "ARS-0043" returns the proper result
- In an "Identifier" search, "ARS.0043" returns the proper result
- **In an "Identifier" search, "ARS0043" does not return a result**

Desired change: an Identifier search for "ARS0043" (no punctuation) should return this collection.
Steps to solve this particular case, and improve Identifier search overall:
1. Analyze the content of existing identifiers: pull the contents of the `ead_ssi` field for all our records in Solr, and document general patterns (I am suggesting to pull `ead_ssi` rather than `id` because it maintains the original punctuation of what's in the `<eadid>` XML field, but they are about the same). 
2. Design a filter approach for Solr that will support decent search across all these patterns.

We might also consider ID cleanup, such as removing "xml" from IDs (for example `sc0097.xml` is an `<eadid>` [in one of our fixture files](https://github.com/sul-dlss/stanford-arclight/blob/c014f56dee02cc3fee8a892703e187eb9a858214/spec/fixtures/ead/uarc/sc0097.xml#L4)). 

Broken out from #451

**Comment by marlo-longley** [comment]
From Cory

Here’s an example in SearchWorks of using a charFilter to replace punctuation using a regex. Removing the .xml or whatever else would work similarly: https://github.com/sul-dlss/SearchWorks/blob/main/config/solr_configs/schema.xml#L485

**Comment by corylown** [comment]
Here are all the ead_ssi values stored in Solr: https://docs.google.com/spreadsheets/d/1AU3X3ppLxwmOi9ar-_d5QVWN3oJLFkRayXwrczdMcyM/edit#gid=0

**Comment by marlo-longley** [comment]
That's awesome, thanks Cory.
My hot take is that filtering out hyphens, underscores, and `.xml` would be a decent start.

**Comment by corylown** [comment]
Taking a closer look at the ArcLight Solr config. The fix here may be as simple as adding the existing `unitid_identifier_match` field to the list of fields searched for an identifier search.

https://github.com/projectblacklight/arclight/blob/d26cd8ff0fed44356987b45751069f069dfac469/solr/conf/schema.xml#L285
