### ISSUE TITLE
Page header

### ISSUE THREAD

**Issue by astridu** [sul-dlss/stanford-arclight#492]
For all pages except landing page.

1. Stanford "stripe": "Stanford University" [Souce Serif 4, Black 100/2E2D29, 16 Semibold], on white background; linked to www.stanford.edu
2. Logo: https://drive.google.com/file/d/11zJPX7fs-PY-cDi7AlmrWMIZmVPUf0h7/view?usp=drive_link (approx 258 x 41 pixels); link to library.stanford.edu; alt text="Stanford Libraries"
3. Green background: 014240
4. Link text: (white since it's on a dark backgound)
  a. Home: Links to sul-arclight.stanford.edu (or whatever the homepage URL will be)
  b. History: Links to history page
  c. Feedback: opens the Feedback form
  d. Login: Logs user into application
5. Page title: "Archival Collections at Stanford" [FFFFFF, Source Sans 3, Semibold, 36pt]
6. "Beta": Rounded corner box [yellow = FEC51D; white text=FFFFFF, Source Serif 4, Regular 14pt]
7. Link text: (white and bold)
  a. Collections: links to Collections home
  b. Repositories: links to Repositories home 
8. Search bar background color: Black 100/2E2D29
  a. "Search" [white, Source Sans 3, Bold, 16pt]
  b. All collections dropdown
  c. All fields dropdown
  d. Search box with font awesome search icon

**Comment by taylor-steve** [comment]
@astridu I have a couple of questions:
- For the beta indicator the ticket says white text, but the design has black text. Which is correct? Currently I'm following the figma design.
- The menu with the "Repositories" and "Collections" has an active indicator available. Do you want to specify any visual difference for the currently active link (e.g., user is currently on that page)?

**Comment by astridu** [comment]
@taylor-steve 
1. Sorry, that was a typo. It should be black.
2. No active indicator
3. We are keeping that! Sorry, I just missed it. 
Thank you for catching those!!
