### ISSUE TITLE
Set up feedback form

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#497]
The designs specify a link to a feedback form: https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=8-23&t=ndOaRifJfhSSLenN-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=6%3A85&show-proto-sidebar=1

Submitting the form should send an email to the arclight-feedback email list

We can copy the pattern from https://github.com/search?q=repo%3Asul-dlss%2Fvt-arclight%20feedback&type=code

**Comment by dinahhandel** [comment]
feedback list address is: arclight-feedback@lists.stanford.edu

**Comment by marlo-longley** [comment]
Closed by #513
