### ISSUE TITLE
Change Date Range facet to slider display

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#523]
A date slider and entry boxes are preferred over a long list of dates in the date range facet. [Michigan does this](https://findingaids.lib.umich.edu/catalog?utf8=%E2%9C%93&group=true&search_field=all_fields&scope=all&q=), sort of, but it appears to be broken?

**Comment by corylown** [comment]
Work Duke did to get blacklight_range_limit working with Blacklight 8: https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/commit/6505798974d4508ced76a1b17dceb5c8bcc5110a
