### ISSUE TITLE
Investigate whether it is possible to link from the image on the landing page to the digital object in the finding aid

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#524]
Currently, the images on the landing page image carousel do not contain a link to either a PURL or the digital object within the finding aid. It would be ideal for the user to click on the image's metadata information displayed beneath the image and be taken to the digital object within the finding aid.

**Comment by dinahhandel** [comment]
FYI, Michigan takes you to the collection's page, which is a nice feature: https://findingaids.lib.umich.edu/catalog

**Comment by taylor-steve** [comment]
@dinahhandel this has been closed now without any featured items in the demo site having links but rest assured that we have this ability now.
