### ISSUE TITLE
Production logging is broken since Rails 7.1 update

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#532]
logs in `/var/log/arclight`

![Image](https://github.com/sul-dlss/stanford-arclight/assets/458247/34d49a5b-eaf8-4508-b051-a62044ea85e1)

**Comment by jcoyne** [comment]
My impression was that logging to STDOUT allowed us to have searchable logs in Cloudwatch, which is preferable to the local Rails logs.

**Comment by corylown** [comment]
@jcoyne my impression is that to send logs to cloudwatch some puppet config is required to watch specific log files. For example, it looks like SearchWorks is configured to send its production application log to CloudWatch: https://github.com/sul-dlss/puppet/blob/production/hieradata/cloudwatch_logs/searchworks.eyaml. If nothing gets written to that log file then no data is sent to CloudWatch. It looks like most of our apps are only sending Apache logs to CloudWatch. We should discuss at our next dev stand-up.

**Comment by jcoyne** [comment]
@corylown logging to STDOUT redirects to the Apache log, so this accomplishes the goal without special cloudwatch configuration in Puppet.
