### ISSUE TITLE
Should the application name in the page title be something other than "Arclight"

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#536]
~~Maybe "Find Archival Materials" or "Archival Collections at Stanford"~~
We've decided on "Archival Collections at Stanford"

![Image](https://github.com/sul-dlss/stanford-arclight/assets/458247/c6478c76-00de-4b6c-b7bb-8ce31c60e21a)

**Comment by dinahhandel** [comment]
Archival Collections at Stanford
