### ISSUE TITLE
Change default when user conducts an empty search from landing page

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#544]
**Decision** -- We decided to set group=true when a person starts a search from any search box in the app. We will not distinguish between searches without/without a query.

<hr>

When a user conducts an "empty" search from the landing page by pressing the search icon, they are taken to the [results page that by default shows all components in ArcLight](https://sul-arclight-demo.stanford.edu/catalog). It would be preferable if the default behavior was for the user to land on "Grouped by collection" after conducting an empty search. FWIW [Michigan](https://findingaids.lib.umich.edu/catalog?utf8=%E2%9C%93&group=true&search_field=all_fields&scope=all&q=) and [Duke](https://archives.lib.duke.edu/catalog?group=true&search_field=all_fields&q=) group by collection.

**Comment by corylown** [comment]
@dinahhandel Duke and Michigan also group by collection if you enter a search term not just an empty search. Do want to always group by collection as the default or only if there is no query or filter applied to the search?

**Comment by dinahhandel** [comment]
@corylown only if there is no query or filter applied to the search.

**Comment by corylown** [comment]
I think there are some UX concerns with this:

1. Person conducts an empty search from the home page and ends up on the results page with everything grouped by collection. Then they put a search term in the search box or apply a filter. Do we then remove the group by collection setting or leave it applied?
2. Person has searched for something from the home page and ends up on a results page with results not grouped by collection. They change to the grouped view then remove the filters or queries they applied, do we retain or remove the grouped by collection setting?

Part of what I'm getting at is we don't have a good way to know if we applied the grouped by collection setting or if the user applied it. It may be confusing for us to automatically change a setting a user applied based on the currently applied query or filters.

**Comment by dinahhandel** [comment]
@corylown I'm not sure I see the functionality as concerning, but I'm not a UX expert :) For your first point, it seems like when things are grouped by collections and the user selects a facet or enters a search term, it shows the collections and their top three results with the search term highlighted or just shows the collections listed, either with the top three results or in the same way they would appear when you usually look at the collection facet. I guess I am saying I am indifferent to whether we remove the group by collection setting or leave it applied after the empty search/when the user initiates a new search from the results page. 

For your second concern, I don't see an issue with retaining grouped by collection, because by removing all the filters and search terms, they are effectively performing an empty search. Am I missing something? 

Happy to huddle and discuss further!

**Comment by corylown** [comment]
The requirement to apply a different grouping behavior when there is a search term and when there isn't makes this tricky. I think what I'm getting at is that this should either be a user controlled setting or something that we let the app set based on current query state (what we would have to do if the presence/absence of a query changes the setting). I think it's confusing to try to make it work both ways. What Duke is doing seems like a sensible compromise. They always group by default when someone uses the search box (with a blank or non-blank search) but otherwise honor the group setting the user applied. Maybe we should discuss at stand-up tomorrow.

**Comment by dinahhandel** [comment]
I would prefer the compromise of always grouping by collection by default over the current behavior.
