### ISSUE TITLE
Design change to Landing page

### ISSUE THREAD

**Issue by astridu** [sul-dlss/stanford-arclight#552]
https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?page-id=0%3A1&type=design&node-id=360-180&viewport=-9127%2C153%2C1&t=tolZlbOe8y81XcGB-1&scaling=min-zoom&starting-point-node-id=6%3A85&mode=design

The main changes:
1. added "Archival Collections at Stanford" below the Stanford Libraries log.
2. Changed background color behind search box and image to light gray [EFEFEF] to green gradient [D0D8D8]
3. Font needs to change to black for the "Find Archival Materials" and "Detailed inventories of [n] collections"
4. Links under the search box are blue

**Comment by marlo-longley** [comment]
Thanks so much @astridu ! I am loving the design. 
Quick question, is it intended that the beta symbol would be in different places on the landing page vs inner pages, now that we've added the "Archival Collections at Stanford" into the landing page? The tag is in two different places now. Thanks.


<img width="714" alt="Screenshot 2024-04-19 at 09 51 50" src="https://github.com/sul-dlss/stanford-arclight/assets/1328900/4b2a1d79-91ec-43a3-beb2-bd67afc8b2c4">
<img width="1404" alt="Screenshot 2024-04-19 at 09 51 58" src="https://github.com/sul-dlss/stanford-arclight/assets/1328900/07f01836-af45-4301-92bd-958b90e8a0aa">

**Comment by astridu** [comment]
Good catch!! It should be in the same place. I updated the Figma file. Thank you!

**Comment by marlo-longley** [comment]
Thanks @astridu. Another question I have is about where and when to use Sentence case in the design. This question applies to the landing page but I guess other pages as well for the app. Gary used to really focus on this so it's burned into my brain!

So in the Figma designs, in the cards, we have "Request materials" and "Contact a Librarian" which seem to use different casing.
<img width="1324" alt="Screenshot 2024-04-19 at 12 48 09" src="https://github.com/sul-dlss/stanford-arclight/assets/1328900/a0b24483-a4af-4ea1-8206-627985132de2">


And then up top we have the headers using all capitalized using not-sentence case "Archival Collections at Stanford"  and "Find Archival Materials" with sentence case below for "About this site". 
<img width="764" alt="Screenshot 2024-04-19 at 12 48 25" src="https://github.com/sul-dlss/stanford-arclight/assets/1328900/ea1f101c-83c2-431e-8f52-882ef9e91887">


If this is all intended thanks for bearing with me! But at standup today we thought it'd be best to double check with you about what rules or guidelines there are around sentence casing for the landing page and in general. Thank you.

**Comment by astridu** [comment]
Another great catch! I updated the following to sentence case: "Find archival materials" and "Contact a librarian"
I left the "Archival Collections at Stanford" title case. I feel like the title of the site warrants title case.
And then the names of the repositories and collections, whenever you all get to those will be title case since those are formal names. Does that sound ok?
