### ISSUE TITLE
Design - Collection home page

### ISSUE THREAD

**Issue by astridu** [sul-dlss/stanford-arclight#565]
Design specs in mockup below. Let me know if you need more detail.

https://www.figma.com/file/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=6%3A122&mode=design&t=3h7BtB8QphzklMp5-1

**Comment by corylown** [comment]
May be completed by #566

**Comment by marlo-longley** [comment]
Yes, I am working on this at the same time @corylown
