### ISSUE TITLE
Design - Collection item page

### ISSUE THREAD

**Issue by astridu** [sul-dlss/stanford-arclight#566]
https://www.figma.com/file/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=13%3A279&mode=design&t=yVur48PFvgiFGvcw-1

**Comment by corylown** [comment]
Most likely we can take care of https://github.com/sul-dlss/stanford-arclight/issues/565 at the same time

**Comment by marlo-longley** [comment]
Todo:
Break out ticket to change color of font-awesome plus sign icon from Core to be blue not black. Not including that in the PR.
