### ISSUE TITLE
Design refinement: Rearrange and restyle paginator

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/stanford-arclight#600]
Broken out of #546 

Needs investigation but this will involve overriding upstream

Astrid's design is [here](https://www.figma.com/file/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=235-132&mode=design&t=qaHiQiqbBwWaAjSh-0) and should look like:
<img width="541" alt="Screenshot 2024-05-08 at 16 32 51" src="https://github.com/sul-dlss/stanford-arclight/assets/1328900/444809d4-fdec-4f99-aa28-8446ac02ea7a">

As of #595, it in fact looks like:
<img width="561" alt="Screenshot 2024-05-08 at 16 18 40" src="https://github.com/sul-dlss/stanford-arclight/assets/1328900/2fb22862-8ddf-4645-9bbf-57f9567ecac6">

**Comment by corylown** [comment]
If that's a kaminari paging widget, it should be pretty easy to configure in our app.
