### ISSUE TITLE
Digital content icon requirements

### ISSUE THREAD

**Issue by astridu** [sul-dlss/stanford-arclight#602]
1. Icon: (slightly lighter green than the header) 2D716F
2. Hover tooltip (same color green, white text, with a drop shadow if possible) "Includes digital content"
<img width="1064" alt="image" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/d4c76a2d-749e-4d35-af73-47ed79a3ed07">

3. Online content button: 
Not selected: Light green background EBF5F1, dark green border on left side 014240
Selected: Light gray background EAEAEA, dark green border on left side 014240, "x" is in link text blue, "Includes digital content"
<img width="353" alt="image" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/b0108e41-2a07-45a0-a7d0-9c9ec8b30d06">

4. Banner on collection home (same styling as button described above), "Digital content - Some content from this collection are available online. View all with digital content"
<img width="913" alt="image" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/278a5ec4-b7c4-467e-ace7-aa53271100a9">

**Comment by marlo-longley** [comment]
Hi @astridu -- thanks. I understand items 1 and 3 here. For 1, this icon doesn't currently show up in search results, so I will have to add it in. 

I am not clear on 2. On what page does this appear? Does it currently exists? Sorry, but I'm not seeing it. Thanks!

**Comment by astridu** [comment]
@marlo-longley Regarding 2, the hover tooltip would appear when a user hovers over the digital content icon, in all the places it appears.

**Comment by astridu** [comment]
@marlo-longley Oh, or maybe you mean 3? That button appears on the Repositories page and Collections page. 
<img width="1195" alt="image" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/919d4923-e18f-4285-b0ed-478b4b5ce15a">
<img width="1195" alt="image" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/48288f83-4de9-42ab-ab74-02e15d328f63">

**Comment by marlo-longley** [comment]
Perfect thank you @astridu

**Comment by marlo-longley** [comment]
@astridu just to confirm, is this digital content button meant to replace the facet for "Online Access" ? Right now it displays as all other facets. 

<img width="1383" alt="Screenshot 2024-05-10 at 11 06 54" src="https://github.com/sul-dlss/stanford-arclight/assets/1328900/7c572e09-351a-45f7-b0f2-f6f01c1e8d85">

<img width="1388" alt="Screenshot 2024-05-10 at 11 09 42" src="https://github.com/sul-dlss/stanford-arclight/assets/1328900/bed6c9ed-5220-49bc-ac25-6536c7e3a253">

**Comment by astridu** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
