### ISSUE TITLE
Remove ::before style on landing page search autocomplete results

### ISSUE THREAD

**Issue by taylor-steve** [sul-dlss/stanford-arclight#604]
I think I caused this...

![Screenshot 2024-05-09 at 8 56 50 AM](https://github.com/sul-dlss/stanford-arclight/assets/4421877/d40988bb-874d-4b5c-9b85-b23d45432a94)

**Comment by marlo-longley** [comment]
@taylor-steve could you explain what the issue is here? Is the width of the search results not wide enough? 
I'm on that page doing styles so I could probably handle it. Thanks.

**Comment by taylor-steve** [comment]
@marlo-longley I don't think the discs should be appearing on those 2:n autocomplete results. I believe it's the style I added for the menu link separator spilling over.

**Comment by marlo-longley** [comment]
@taylor-steve thanks, got it!
