### ISSUE TITLE
Display public beta information more prominently

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#611]
Prominent banner on each page of the UI that this is a public beta and that Online Archive of California (https://oac.cdlib.org/institutions/Stanford+University) is the place to go for the most up to date information and for making requests.

Furthermore, we'd like to indicate that the data source for University Archives, Manuscripts, and Rare Books is the Online Archive of California and when it was last updated. And that the data source for EAL, ARS, and Cubberley is ArchivesSpace and is up to date. Not sure if it's best to display this with the repository information or with each collection.

**Comment by astridu** [comment]
For the banner that appears on each page of the site, what do you think of this?

Homepage: https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?page-id=0%3A1&type=design&node-id=360-180&viewport=-2755%2C205%2C0.5&t=Io52juv4DtMAJbvI-1&scaling=min-zoom&starting-point-node-id=360%3A180&show-proto-sidebar=1

Repositories page: https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?page-id=0%3A1&type=design&node-id=8-23&viewport=-2755%2C205%2C0.5&t=Io52juv4DtMAJbvI-1&scaling=min-zoom&starting-point-node-id=8%3A23&show-proto-sidebar=1

**Comment by astridu** [comment]
And if we continue the yellow color theme for beta messages, this is what it would look like on the collection home page:
https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?page-id=0%3A1&type=design&node-id=6-122&viewport=-2755%2C205%2C0.5&t=Io52juv4DtMAJbvI-1&scaling=min-zoom&starting-point-node-id=6%3A122&show-proto-sidebar=1

And the individual repository page: https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?page-id=0%3A1&type=design&node-id=62-86&viewport=-2755%2C205%2C0.5&t=Io52juv4DtMAJbvI-1&scaling=min-zoom&starting-point-node-id=62%3A86&show-proto-sidebar=1

It is very stripey and yellow! Does it need that prominence, or is something like the mockup below work, where we just put an asterisk next to the note?
<img width="1186" alt="image" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/2c024baf-ad39-408e-970d-75655e145c89">
<img width="1089" alt="image" src="https://github.com/sul-dlss/stanford-arclight/assets/42216982/464ded9e-8ddd-45b3-a31e-09e740492c0e">

**Comment by dinahhandel** [comment]
Could we change "Go to" to "Please visit the Online..." Otherwise, I think this looks good. My other suggestion would be for OAC data, it would be nice to show a "last updated" date.

**Comment by astridu** [comment]
Could we say "Visit the Online..." Since we already have a 'Please' at the beginning of the paragraph?

**Comment by dinahhandel** [comment]
@astridu yes! Thanks for catching that!

**Comment by corylown** [comment]
I'm going to break this up into two issues. One for adding the new banner and another for the collection source/currency.
