### ISSUE TITLE
Do we have all the okcomputer checks we want

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#646]
Look at DLME & VT Arclight for examples of what to track.

**Comment by marlo-longley** [comment]
Looks like for VT we had something more complex but then reverted to just the basic up-ness check:
https://github.com/sul-dlss/vt-arclight/commit/eab278597adf9049bbdfc9ef120cf9d7c0935b4a

**Comment by corylown** [comment]
I seem remember some discussion about that from way back. Maybe what we have already is fine? Nagios will alert if any of the redis or db VMs are flipping out.

**Comment by corylown** [comment]
Maybe what we really want to ensure is that nagios is checking for a 200 from the webapp.

**Comment by taylor-steve** [comment]
Opened an issue with ops: https://github.com/sul-dlss/operations-tasks/issues/3764

**Comment by taylor-steve** [comment]
Ops has added the webapp check to nagios. Do we want anything else for this issue?

**Comment by corylown** [comment]
@taylor-steve this can be closed now. Thank you.
