### ISSUE TITLE
Add public beta banner

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#657]
Should appear on all pages of the application. Might be convenient to be able to turn this on/off via a setting.

Text should be:

Please note this is a public beta version of this application. Visit the Online Archive of California for the most up to date information and to make a request.

Figma mockups:

- Landing page: https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?page-id=0%3A1&type=design&node-id=360-180&viewport=-2755%2C205%2C0.5&t=Io52juv4DtMAJbvI-1&scaling=min-zoom&starting-point-node-id=360%3A180&show-proto-sidebar=1
- Repositories page: https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?page-id=0%3A1&type=design&node-id=8-23&viewport=-2755%2C205%2C0.5&t=Io52juv4DtMAJbvI-1&scaling=min-zoom&starting-point-node-id=8%3A23&show-proto-sidebar=1

Part of: https://github.com/sul-dlss/stanford-arclight/issues/611

**Comment by taylor-steve** [comment]
@astridu or @corylown are we removing the beta pill as part of this? I don't see it in the designs, but I didn't see it specifically mentioned to remove. Thanks.
![Screenshot 2024-05-21 at 4 13 28 PM](https://github.com/sul-dlss/stanford-arclight/assets/4421877/6b7ab972-ed75-4070-aec8-abd4c61bf450)

**Comment by astridu** [comment]
@corylown @dinahhandel I assumed since we were doing the banner, we would remove the pill, but I am doublechecking with you.

**Comment by dinahhandel** [comment]
@astridu from your perspective, what is best? I could see leaving it because it makes it really obvious... But I also defer to what you think!

**Comment by taylor-steve** [comment]
I can easily hook it up to an on/off setting like we're doing with the banner, if we want.

**Comment by astridu** [comment]
I think the beta banner is enough of an alert that we don't need the pill as well. Thank you!
