### ISSUE TITLE
When I try to download a PDF finding aid my computer tells me the file is broken 

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#660]
I just tried to download the PDF finding aid from the [Allen Ginsberg collection](https://archives.stanford.edu/catalog/m0733-xml_allen-ginsberg-papers) and I’m not able to open it on my computer. I get a message in both Preview and Adobe Acrobat Reader that the file is damaged.

So far, after randomly selecting and testing ~15 other finding aids from OAC data, I am not getting the same error.

**Comment by taylor-steve** [comment]
I think this will be completed by:
https://github.com/sul-dlss/stanford-arclight/pull/663
#672 

Once prod has a new release, we should double check that the scheduled `GeneratePdfJob.enqueue_all_missing_and_invalid` job correctly regenerated the PDF referenced above. Stage is creating it just fine, so I'm optimistic.

**Comment by taylor-steve** [comment]
@corylown when you get a chance, I'd be curious on your thoughts on what direction to go with #697. No rush, I just think this one is on hold until we decide. If RAM is a scarce resource, I think lowering the number of sidekiq processes and increasing threads on the default queue to compensate would work totally fine.

**Comment by corylown** [comment]
@taylor-steve I set aside some time tomorrow morning to think this over and I'll respond here and/or discuss at post standup.

**Comment by corylown** [comment]
@taylor-steve I think it's totally reasonable for us to request that ops increase the RAM available on sul-arclight-prod-* and sul-arclight-stage-* to 8GB to address this.

**Comment by taylor-steve** [comment]
Great, thanks. Requested: https://github.com/sul-dlss/operations-tasks/issues/3774
