### ISSUE TITLE
Collection contents not loading for M2651 Bernice Bing papers

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#661]
I am having trouble clicking on the collection contents from this collection: https://archives.stanford.edu/catalog/bernice-bing-papers. 

Via Slack, @taylor-steve writes "Getting turbo fetch/CORS failures. Anybody else?"

**Comment by corylown** [comment]
This should be fixed by https://github.com/sul-dlss/stanford-arclight/commit/009fee2610dc90bf9e6b36cd1bffd3a6e3d9d70c once it's released. This will happen for any collection without an eadid.
