### ISSUE TITLE
Can we remove the requirement that Aspace resources have an ead_id?

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#666]
We're forming identifiers in Arclight from the ead id and the title and an ead id is no longer strictly required for the application to function. Can we remove the requirement from the ASpace resource query that a finding aid have an ead id to allow harvesting? Could we fall back to the unit id?

https://github.com/sul-dlss/stanford-arclight/blob/8a442b978ef986201da033ec49b3191620689f1e/app/services/aspace_query.rb#L65

**Comment by marlo-longley** [comment]
@corylown I didn't realize you were working on this -- I am currently writing some code around this issue for my download work.

**Comment by marlo-longley** [comment]
In `resource.rb` I wrote the following, and handle the fallout throughout the app 

```
    def normalized_id
      return ead_id if ead_id

      resource_id = uri.split("/")[-1]
      resource_name = "resource_" + resource_id
      return resource_name
    end
```
