### ISSUE TITLE
Feedback emails should generate an issue in Jira queue (work with ops)

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#680]

**Comment by corylown** [comment]
Operations Task issue: https://github.com/sul-dlss/operations-tasks/issues/3767

**Comment by dinahhandel** [comment]
JIRA ticket created, testing to see if email creates ticket: https://jirasul.stanford.edu/jira/projects/ARCLIGHT/issues/ARCLIGHT-1?filter=allopenissues

**Comment by dinahhandel** [comment]
This work is done, closing ticket.
