### ISSUE TITLE
Fix cron mail delivery failures

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#683]
Seeing errors when cron generates mail on:
`sul-arclight-prod-a`
`sul-arclight-stage-a`

Example: 

```
Delivery has failed to these recipients or groups:

[arclight@sul-arclight-stage-a.localdomain](mailto:arclight@sul-arclight-stage-a.localdomain)
Your message wasn't delivered because the recipient's email provider rejected it.
```

**Comment by taylor-steve** [comment]
I'm seeing stage and prod don't have localhost defined in `/etc/hosts`, which says it is managed by puppet but for the life of me I can't figure out where.

Some servers have `profile::postfix::domain: 'stanford.edu'` configured, but most don't?

Either of these seem likely/ring a bell? I can ask ops again if not.

**Comment by corylown** [comment]
I'm not sure...

**Comment by taylor-steve** [comment]
Same. https://github.com/sul-dlss/operations-tasks/issues/3776

**Comment by taylor-steve** [comment]
No failures over the past week. I've set reminders to check this, will re-open if it pops back up.
