### ISSUE TITLE
Hours cache isn't expiring at the right time

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#685]
We're expecting the hours display cache to expire on the hour and half hour but this morning we found the hours display was showing the libraries were closed when they should have been open.

**Comment by corylown** [comment]
I wonder if this is a Time.now vs Time.current issue. On sul-arclight-prod-a I get slightly different answers:

```
3.3.0 :001 > Time.now.to_f
 => 1716927219.8939943 
3.3.0 :002 > Time.current.to_f
 => 1716927224.9757571 
```

**Comment by corylown** [comment]
But the expiration time looks okay:
```
3.3.0 :020 > (Time.current.at_beginning_of_hour + (Time.current.min < 30 ? 30.minutes : 60.minutes)).to_f
 => 1716928200.0 
3.3.0 :021 > Rails.cache.send(:read_entry, 'views/landing_page/_cards:2de8cc75cc02aa10e3b2c517d27da179/location_hours')&.expires_at
 => 1716928200.0000353 
```

**Comment by taylor-steve** [comment]
Nice thanks, this is the direction I'm looking now. I have redis caching enabled on local dev and the correct markup is being cached for the time period I'd expect. I'm wondering if timezones are in play somehow

**Comment by taylor-steve** [comment]
Okay maybe it's only correct half of the time. It just invalidated locally, and the new cache is good for 490 years...

**Comment by taylor-steve** [comment]
I think this honeybadger alert supports the case that the current fix, to avoid setting cache expiry times in the past/extremely near future, addresses this issue. I've been spot checking prod since the fix went in and the cache times are as expected. I'm happy to call this one closed, unless there are other concerns.

**Comment by corylown** [comment]
Let's close it and reopen if it comes up again.
