### ISSUE TITLE
Collapsed Feedback form should not receive keyboard focus

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/stanford-arclight#734]
Appears on https://archives.stanford.edu and https://virtualtribunals.stanford.edu.

### Expected behavior

When the Feedback form (in the header) is collapsed, the hidden-from-view content should not receive keyboard focus. Tab/Shift+Tab or screen reader navigation should not interact with the Feedback form content when collapsed.

### Current behavior

The hidden-from-view Feedback form receives keyboard focus when collapsed.

### Steps to reproduce

Use Tab/Shift+Tab keys or a screen reader to navigate through header with the Feedback form collapsed.

### Possible solution

Toggle `display: none;` on the "feedback" `<div>` when collapsed.

**Comment by taylor-steve** [comment]
Thanks for catching this @alundgard. We have a fix in place, currently visible on https://sul-arclight-demo.stanford.edu/, that seems to address the keyboard focus issue. I haven't tested using a screen reader. We'll apply a similar fix for VT soon.

**Comment by alundgard** [comment]
Great, I tried it out with VoiceOver and Tab navigation. Looks good to me!
